version: '3.8'
services:

  postgres_notifications:
    image: postgres:15.1-alpine
    container_name: postgres_notifications
    volumes:
      - postgres_notifications_data:/var/lib/postgresql/data/
      - ./config/sql/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
    restart: always
    env_file:
      - config/.env

  redis_notifications:
    image: redis:7.0.5-alpine
    container_name: redis_notifications
    volumes:
      - redis_notifications_data:/data
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - config/.env


  admin_notifications:
    container_name: admin_notifications
    build: .
    command: /bin/bash -c "gunicorn --bind 0.0.0.0:5000 config.wsgi:application"
    volumes:
      - admin_notifications_data:/data
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - config/.env
    depends_on:
      - redis_notifications
      - postgres_notifications


volumes:
  postgres_notifications_data:
  redis_notifications_data:
  admin_notifications_data: